-- demo
CREATE TABLE `demo`(
	`id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
	`name` VARCHAR(32) DEFAULT NULL COMMENT '名字',
	`age` INT DEFAULT NULL COMMENT '年龄',
	`creater` VARCHAR(64) DEFAULT NULL COMMENT '新增者' ,
	`gmt_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
	`modifier` VARCHAR(64) DEFAULT NULL COMMENT '修改者' ,
	`gmt_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
)COMMENT = 'demo';



